import type { Comment, UserSummary, Video } from "@/types/api";

export const currentUser: UserSummary = {
  id: 99,
  username: "aziz.builder",
  avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
  bio: "Building XSpann RNB one clean release at a time.",
  verified: true,
};

export const creators: UserSummary[] = [
  {
    id: 1,
    username: "jessica.luv",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
    bio: "Neon city edits and dance clips.",
    verified: true,
  },
  {
    id: 2,
    username: "alexjordan",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=160&q=80",
    bio: "Street style, travel, and sound loops.",
    verified: true,
  },
  {
    id: 3,
    username: "sarah.k",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80",
    bio: "Quiet luxury fits and purple-hour reels.",
  },
  {
    id: 4,
    username: "michael.lee",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80",
    bio: "Creator tools and daily edits.",
    verified: true,
  },
];

export const videos: Video[] = [
  {
    id: 1001,
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85",
    caption: "Good vibes only. Purple hour hit different tonight.",
    duration: 15,
    status: "published",
    user: creators[0],
    stats: { views: 920000, likes: 128700, comments: 1234, saves: 8456, shares: 2345 },
    viewer: { liked: true, saved: false, following: false },
    sound_name: "Original sound",
    sound_artist: "jessica.luv",
    sound_provider: "original",
    sound_external_id: null,
    sound_preview_url: null,
    music: "original sound - jessica.luv",
    tags: ["fyp", "xspannrnb", "goodvibes"],
    location_name: "Pabna",
    visibility: "public",
    high_quality_upload: true,
    scheduled_at: null,
    pinned_at: null,
    edit: { trim_start: 0, trim_end: null, cover_time: null, crop_mode: "fill", text_overlay: null, original_audio_muted: false },
    created_at: "2026-09-02T08:15:00Z",
  },
  {
    id: 1002,
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
    caption: "Saved this ocean walk for the timeline.",
    duration: 22,
    status: "published",
    user: creators[1],
    stats: { views: 310000, likes: 76200, comments: 822, saves: 3920, shares: 1198 },
    viewer: { liked: false, saved: true, following: true },
    sound_name: "Midnight City Loop",
    sound_artist: "alexjordan",
    sound_provider: "local",
    sound_external_id: null,
    sound_preview_url: null,
    music: "midnight city loop - alexjordan",
    tags: ["travel", "ocean", "vertical"],
    location_name: "Cox's Bazar Sea Beach",
    visibility: "public",
    high_quality_upload: true,
    scheduled_at: null,
    pinned_at: null,
    edit: { trim_start: 0, trim_end: null, cover_time: null, crop_mode: "fill", text_overlay: null, original_audio_muted: false },
    created_at: "2026-09-01T19:04:00Z",
  },
  {
    id: 1003,
    video_url: null,
    thumbnail_url: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85",
    caption: "Outfit check before the rain starts.",
    duration: 18,
    status: "published",
    user: creators[2],
    stats: { views: 188000, likes: 44200, comments: 519, saves: 2120, shares: 704 },
    viewer: { liked: false, saved: false, following: false },
    sound_name: "Soft Flash",
    sound_artist: "sarah.k",
    sound_provider: "local",
    sound_external_id: null,
    sound_preview_url: null,
    music: "soft flash - sarah.k",
    tags: ["style", "ootd", "purple"],
    location_name: "Dhaka",
    visibility: "public",
    high_quality_upload: true,
    scheduled_at: null,
    pinned_at: null,
    edit: { trim_start: 0, trim_end: null, cover_time: null, crop_mode: "fill", text_overlay: null, original_audio_muted: false },
    created_at: "2026-08-31T13:20:00Z",
  },
];

export const comments: Comment[] = [
  {
    id: 1,
    video_id: 1001,
    parent_id: null,
    body: "This color grade is clean.",
    user: creators[1],
    created_at: "2m ago",
  },
  {
    id: 2,
    video_id: 1001,
    parent_id: null,
    body: "Royal purple theme fits XSpann RNB so well.",
    user: creators[3],
    created_at: "8m ago",
  },
  {
    id: 3,
    video_id: 1001,
    parent_id: null,
    body: "Saved for my next upload inspiration.",
    user: currentUser,
    created_at: "12m ago",
  },
];

export const trendingTags = ["#xspannrnb", "#royalpurple", "#creatorflow", "#nightcity", "#verticalvideo"];
